apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: cloudshelf
data:
  NEXT_PUBLIC_API_BASE: "http://${PUBLIC_IP}:32250/api"
  NEXT_PUBLIC_GRAPHQL_ENDPOINT: "http://${PUBLIC_IP}:32250/api/graphql"
  NEXT_PUBLIC_AUTHORS_ENDPOINT: "http://${PUBLIC_IP}:32250/api/authors"
  NODE_ENV: "production"
  NEXT_TELEMETRY_DISABLED: "1"